# Generated by Django 5.2.4 on 2025-07-27 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место, в котором необходимо выполнять привычку",
                        max_length=200,
                        null=True,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        help_text="Укажите время, когда необходимо выполнять привычку",
                        null=True,
                        verbose_name="Время",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text="Укажите действие, которое представляет собой привычка",
                        max_length=200,
                        null=True,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Привычка, которую можно привязать к выполнению полезной привычки",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "frequency_days",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Интервал выполнения (1-7 дней)", verbose_name="Периодичность в днях"
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=200, null=True, verbose_name="Вознаграждение")),
                (
                    "lead_time",
                    models.TimeField(
                        blank=True,
                        help_text="Укажите время, достаточное для выполнения привычки",
                        null=True,
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Активировать, если привычку можно публиковать в общий доступ",
                        verbose_name="Публичная привычка",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания привычки")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время обновления привычки")),
                (
                    "reward_habit",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_pleasant": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Привычка-вознаграждение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("frequency_days__gte", 1), ("frequency_days__lte", 7)),
                        name="check_frequency_range",
                    )
                ],
            },
        ),
    ]
