# Generated by Django 5.2.4 on 2025-07-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency_days",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Интервал выполнения (1-7 дней)", verbose_name="Периодичность в днях в неделю"
            ),
        ),
    ]
