# Generated by Django 5.2.4 on 2025-07-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                choices=[("Ежедневно", "Ежедневно"), ("Еженедельно", "Еженедельно")],
                default="Ежедневно",
                help_text="Установите периодичность выполнения",
                max_length=20,
                verbose_name="Периодичность",
            ),
        ),
    ]
