# Generated by Django 5.2.4 on 2025-07-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_habit_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("Ежедневно", "Ежедневно"),
                    ("Каждые 2 дня", "Каждые 2 дня"),
                    ("Каждые 3 дня", "Каждые 3 дня"),
                    ("Каждые 4 дня", "Каждые 4 дня"),
                    ("Каждые 5 дней", "Каждые 5 дней"),
                    ("Каждые 6 дней", "Каждые 6 дней"),
                    ("Еженедельно", "Еженедельно"),
                ],
                default="Ежедневно",
                help_text="Установите периодичность выполнения",
                max_length=20,
                verbose_name="Периодичность",
            ),
        ),
    ]
