# Generated by Django 5.2.4 on 2025-08-04 09:31

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_frequency_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(
                default=82,
                help_text="Укажите действие, которое представляет собой привычка",
                max_length=200,
                verbose_name="Действие",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Интервал выполнения (1-7 дней)",
                null=True,
                verbose_name="Периодичность в днях в неделю",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="lead_time",
            field=models.DurationField(
                blank=True,
                help_text="Укажите время, достаточное для выполнения привычки (максимум 2 минуты)",
                null=True,
                verbose_name="Время на выполнение",
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(("frequency_days__isnull", False), ("is_pleasant", True), _connector="OR"),
                name="frequency_required_for_useful",
                violation_error_message="Для полезной привычки поле 'Периодичность' обязательно для заполнения!",
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lead_time__isnull", True), ("lead_time__lte", datetime.timedelta(seconds=120)), _connector="OR"
                ),
                name="max_lead_time_2min",
                violation_error_message="Время выполнения не должно превышать 2 минуты!",
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_pleasant", True), ("lead_time__isnull", False), _connector="OR"),
                name="lead_time_required_for_useful",
                violation_error_message="Для полезной привычки поле 'Время на выполнение' обязательно для заполнения",
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_pleasant", False),
                    models.Q(("is_pleasant", True), ("reward_habit__isnull", True)),
                    _connector="OR",
                ),
                name="pleasant_habit_no_reward_habit",
                violation_error_message="У приятной привычки не может быть связанной привычки",
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_pleasant", False), models.Q(("is_pleasant", True), ("reward__isnull", True)), _connector="OR"
                ),
                name="pleasant_habit_no_reward",
                violation_error_message="У приятной привычки не может быть вознаграждения",
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_pleasant", True),
                    models.Q(("is_pleasant", False), ("reward_habit__isnull", False), ("reward__isnull", True)),
                    models.Q(("reward_habit__isnull", True), ("reward__isnull", False)),
                    models.Q(("reward__isnull", True), ("reward_habit__isnull", True)),
                    _connector="OR",
                ),
                name="useful_habit_reward_logic",
                violation_error_message="У полезной привычки может быть либо связанная приятная привычка, либо вознаграждение!",
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(("time__isnull", False), ("is_pleasant", True), _connector="OR"),
                name="time_required_for_useful",
                violation_error_message="Для полезной привычки поле 'Время' обязательно для заполнения",
            ),
        ),
        migrations.AlterConstraint(
            model_name="habit",
            name="check_frequency_range",
            constraint=models.CheckConstraint(
                condition=models.Q(("frequency_days__gte", 1), ("frequency_days__lte", 7)),
                name="check_frequency_range",
                violation_error_message="Периодичность может быть от 1 до 7 дней в неделю!",
            ),
        ),
    ]
