# Generated by Django 5.2.4 on 2025-08-06 18:34

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_action_alter_habit_frequency_days_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="habit",
            name="frequency_required_for_useful",
        ),
        migrations.RemoveConstraint(
            model_name="habit",
            name="time_required_for_useful",
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=1,
                help_text="Укажите интервал выполнения (1-7 дней)",
                null=True,
                verbose_name="Периодичность в днях в неделю",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="lead_time",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(seconds=120),
                help_text="Укажите время, достаточное для выполнения привычки (максимум 2 минуты)",
                null=True,
                verbose_name="Время на выполнение",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                blank=True,
                default=datetime.time(12, 0),
                help_text="Укажите время, когда необходимо выполнять привычку",
                null=True,
                verbose_name="Время",
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_pleasant", True), ("frequency_days__isnull", False), _connector="OR"),
                name="frequency_required_for_useful",
                violation_error_message="Для полезной привычки поле 'Периодичность' обязательно для заполнения!",
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_pleasant", True), ("time__isnull", False), _connector="OR"),
                name="time_required_for_useful",
                violation_error_message="Для полезной привычки поле 'Время' обязательно для заполнения",
            ),
        ),
    ]
